/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pss.exercicioavaliativopss.view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author handaniels
 */
public class ConfiguracoesView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfiguracoesView
     */
    public ConfiguracoesView() {
        initComponents();
        bgpLogs.add(rbtCSV);
        bgpLogs.add(rbtJSON);
        bgpLogs.add(rbtXML);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpLogs = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtCSV = new javax.swing.JRadioButton();
        rbtJSON = new javax.swing.JRadioButton();
        rbtXML = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel1.setText("Arquivo de Logs");

        rbtCSV.setText("CSV");

        rbtJSON.setText("JSON");

        rbtXML.setText("XML");

        btnSalvar.setText("Salvar");

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtCSV)
                                .addGap(18, 18, 18)
                                .addComponent(rbtJSON)
                                .addGap(18, 18, 18)
                                .addComponent(rbtXML))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtCSV)
                    .addComponent(rbtJSON)
                    .addComponent(rbtXML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ButtonGroup getBgpLogs() {
        return bgpLogs;
    }

    public void setBgpLogs(ButtonGroup bgpLogs) {
        this.bgpLogs = bgpLogs;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public void setBtnFechar(JButton btnFechar) {
        this.btnFechar = btnFechar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }

    public JRadioButton getRbtCSV() {
        return rbtCSV;
    }

    public void setRbtCSV(JRadioButton rbtCSV) {
        this.rbtCSV = rbtCSV;
    }

    public JRadioButton getRbtJSON() {
        return rbtJSON;
    }

    public void setRbtJSON(JRadioButton rbtJSON) {
        this.rbtJSON = rbtJSON;
    }

    public JRadioButton getRbtXML() {
        return rbtXML;
    }

    public void setRbtXML(JRadioButton rbtXML) {
        this.rbtXML = rbtXML;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpLogs;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtCSV;
    private javax.swing.JRadioButton rbtJSON;
    private javax.swing.JRadioButton rbtXML;
    // End of variables declaration//GEN-END:variables
}
